version: '3.8'

services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: crm_db
      POSTGRES_USER: crm_user
      POSTGRES_PASSWORD: crm_password
    ports:
      - "5432:5432"
    volumes:
      - crm_data_volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U crm_user -d crm_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://crm_user:crm_password@db:5432/crm_db
      - WHATSAPP_GATEWAY_URL=http://whatsapp_gateway:3002
    volumes:
      - ./backend:/app # Binding mount for local code changes
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ["sh", "-c", "uvicorn app.main:app --host 0.0.0.0 --port 8000"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000 # Assuming backend runs on localhost:8000
      NEXT_PUBLIC_WHATSAPP_GATEWAY_URL: http://localhost:3002
    volumes:
      - /app/node_modules # Exclude node_modules from bind mount
    depends_on:
      backend:
        condition: service_started

  whatsapp_gateway:
    build:
      context: ./whatsapp_gateway
      dockerfile: Dockerfile
    ports:
      - "3002:3002" # Assuming WhatsApp gateway runs on port 3002
    environment: {}
    volumes:
      - ./whatsapp_gateway:/app
      - ./whatsapp_gateway/user_sessions:/app/user_sessions # Persist session data
    depends_on:
      backend:
        condition: service_started

volumes:
  crm_data_volume:
