"""Add options column to custom_fields

Revision ID: 381bdc18f7bb
Revises: db761699e4dd
Create Date: 2025-10-09 22:24:00.716276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '381bdc18f7bb'
down_revision: Union[str, Sequence[str], None] = 'db761699e4dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_fields', sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_fields', 'options')
    # ### end Alembic commands ###
