"""add_media_type_and_transcription_to_messages

Revision ID: 7bcbe51c9702
Revises: 87b0fac89fd9
Create Date: 2025-10-19 17:01:21.528907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bcbe51c9702'
down_revision: Union[str, Sequence[str], None] = '87b0fac89fd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('media_type', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('transcription', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'transcription')
    op.drop_column('messages', 'media_type')
    # ### end Alembic commands ###
