"""add_telegram_message_id_to_messages

Revision ID: 87b0fac89fd9
Revises: 0e6263bda5fc
Create Date: 2025-10-19 11:39:01.437177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87b0fac89fd9'
down_revision: Union[str, Sequence[str], None] = '0e6263bda5fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('telegram_message_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_messages_telegram_message_id'), 'messages', ['telegram_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_telegram_message_id'), table_name='messages')
    op.drop_column('messages', 'telegram_message_id')
    # ### end Alembic commands ###
