"""Add telegram_chat_id to Customer model

Revision ID: bfd2feb9a6c7
Revises: add_ai_prompts_table
Create Date: 2025-10-17 18:23:39.497630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bfd2feb9a6c7'
down_revision: Union[str, Sequence[str], None] = 'add_ai_prompts_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_ai_prompts_id'), table_name='ai_prompts')
    op.drop_index(op.f('idx_ai_prompts_user_id'), table_name='ai_prompts')
    op.alter_column('custom_entity_records', 'data',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               nullable=True,
               postgresql_using='data::json')
    op.create_index(op.f('ix_custom_entity_records_entity_type_id'), 'custom_entity_records', ['entity_type_id'], unique=False)
    op.create_index(op.f('ix_custom_entity_records_user_id'), 'custom_entity_records', ['user_id'], unique=False)
    op.alter_column('custom_entity_types', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('ix_custom_entity_types_name'), table_name='custom_entity_types')
    op.create_index(op.f('ix_custom_entity_types_user_id'), 'custom_entity_types', ['user_id'], unique=False)
    op.alter_column('custom_fields', 'is_searchable',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('custom_fields', 'options',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='options::json')
    op.drop_constraint(op.f('custom_fields_field_key_key'), 'custom_fields', type_='unique')
    op.create_unique_constraint('_entity_type_field_key_uc', 'custom_fields', ['entity_type_id', 'field_key'])
    op.create_index(op.f('ix_custom_fields_entity_type_id'), 'custom_fields', ['entity_type_id'], unique=False)
    op.create_foreign_key(None, 'custom_fields', 'custom_entity_types', ['reference_entity_type_id'], ['id'])
    op.add_column('customers', sa.Column('telegram_chat_id', sa.Text(), nullable=True))
    op.drop_index(op.f('idx_knowledge_bases_category'), table_name='knowledge_bases')
    op.drop_index(op.f('idx_knowledge_bases_id'), table_name='knowledge_bases')
    op.drop_index(op.f('idx_knowledge_bases_is_active'), table_name='knowledge_bases')
    op.drop_index(op.f('idx_knowledge_bases_user_id'), table_name='knowledge_bases')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_knowledge_bases_user_id'), 'knowledge_bases', ['user_id'], unique=False)
    op.create_index(op.f('idx_knowledge_bases_is_active'), 'knowledge_bases', ['is_active'], unique=False)
    op.create_index(op.f('idx_knowledge_bases_id'), 'knowledge_bases', ['id'], unique=False)
    op.create_index(op.f('idx_knowledge_bases_category'), 'knowledge_bases', ['category'], unique=False)
    op.drop_column('customers', 'telegram_chat_id')
    op.drop_constraint(None, 'custom_fields', type_='foreignkey')
    op.drop_index(op.f('ix_custom_fields_entity_type_id'), table_name='custom_fields')
    op.drop_constraint('_entity_type_field_key_uc', 'custom_fields', type_='unique')
    op.create_unique_constraint(op.f('custom_fields_field_key_key'), 'custom_fields', ['field_key'], postgresql_nulls_not_distinct=False)
    op.alter_column('custom_fields', 'options',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('custom_fields', 'is_searchable',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_custom_entity_types_user_id'), table_name='custom_entity_types')
    op.create_index(op.f('ix_custom_entity_types_name'), 'custom_entity_types', ['name'], unique=True)
    op.alter_column('custom_entity_types', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_custom_entity_records_user_id'), table_name='custom_entity_records')
    op.drop_index(op.f('ix_custom_entity_records_entity_type_id'), table_name='custom_entity_records')
    op.alter_column('custom_entity_records', 'data',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=False)
    op.create_index(op.f('idx_ai_prompts_user_id'), 'ai_prompts', ['user_id'], unique=False)
    op.create_index(op.f('idx_ai_prompts_id'), 'ai_prompts', ['id'], unique=False)
    # ### end Alembic commands ###
